# Generated by Django 3.1.7 on 2021-03-18 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dupont_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchupdates',
            name='blog_image',
            field=models.ImageField(upload_to='media/blog_img'),
        ),
        migrations.CreateModel(
            name='MachineLearningModelReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/references')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
