# Generated by Django 3.1.7 on 2021-03-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dupont_app', '0003_auto_20210318_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=225)),
                ('email_address', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=64)),
                ('phone_no', models.IntegerField()),
                ('contact_prefer', models.BooleanField(default='1')),
                ('question', models.TextField()),
                ('receive_alerts', models.BooleanField(default='0')),
            ],
        ),
    ]
