# Generated by Django 3.1.7 on 2021-03-18 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dupont_app', '0004_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='researchUpdates',
            new_name='researchUpdate',
        ),
    ]
