# Generated by Django 3.1.7 on 2021-03-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dupont_app', '0005_auto_20210318_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactus',
            new_name='Contact',
        ),
    ]
